name: beers
version: 0.0.1
description: >-
  This project was created to learn Dart basics.
author: John Nolette <john@neetgroup.net>
homepage: https://github.com/neetjn/dart-beers
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  aqueduct: '<=3.1.0+1'
  colorize: any
dev_dependencies:
  test: any
  aqueduct_test: any
